// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSqv8GaEyREeS0Z_3mgl4XLp-OKvn8Q3Q',
    appId: '1:225444376351:web:a086db384130a457618a2a',
    messagingSenderId: '225444376351',
    projectId: 'cvboxapp-4ea74',
    authDomain: 'cvboxapp-4ea74.firebaseapp.com',
    storageBucket: 'cvboxapp-4ea74.firebasestorage.app',
    measurementId: 'G-J1F1KSHZE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBore4iuMROTmtt1zFEvzLrMPixrxYkQ84',
    appId: '1:225444376351:android:99d1535ff0caf304618a2a',
    messagingSenderId: '225444376351',
    projectId: 'cvboxapp-4ea74',
    storageBucket: 'cvboxapp-4ea74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsd6o2-3EHyQ5UW9GfHLzI0bAu4jAmu4',
    appId: '1:225444376351:ios:0ddac661b4e8d925618a2a',
    messagingSenderId: '225444376351',
    projectId: 'cvboxapp-4ea74',
    storageBucket: 'cvboxapp-4ea74.firebasestorage.app',
    iosBundleId: 'store.cvbox.cvBox',
  );
}
